# Generated by Django 2.2.9 on 2020-08-30 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='名前')),
            ],
            options={
                'verbose_name': '子カテゴリー',
                'verbose_name_plural': '子カテゴリー',
            },
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='名前')),
            ],
            options={
                'verbose_name': '親カテゴリー',
                'verbose_name_plural': '親カテゴリー',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='サムネ画像')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名前')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='価格')),
                ('description1', models.TextField(blank=True, null=True, verbose_name='商品説明1')),
                ('description2', models.TextField(blank=True, null=True, verbose_name='商品説明2')),
                ('description3', models.TextField(blank=True, null=True, verbose_name='商品説明3')),
                ('child_category', models.ManyToManyField(blank=True, null=True, related_name='child_category', to='backend.ChildCategory', verbose_name='子カテゴリー')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='backend.ParentCategory', verbose_name='親カテゴリー')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='商品画像')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='backend.Product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品画像',
                'verbose_name_plural': '商品画像',
            },
        ),
        migrations.CreateModel(
            name='ProductCompositionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='backend.Product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '成分表',
                'verbose_name_plural': '成分表',
            },
        ),
        migrations.AddField(
            model_name='childcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='backend.ParentCategory', verbose_name='親カテゴリー'),
        ),
    ]
